checks:
  "hello world":
    function: mock
    kwargs:
      return_value: "Hello world."
  "always trigger":
    function: mock
    kwargs:
      return_value: "This check always triggers"
      return_trigger: true
  "always fail":
    function: mock
    kwargs:
      return_value: "This check always raises an exception (this should not be returned)"
      always_fail: true
monitoring:
  status_file: "./status.yaml"
  mail_to: []
  intervals_hours:
    not_triggering: 72
    when_triggering: 4
