name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions
permissions: {}

jobs:

  examples:
    runs-on: ubuntu-latest

    services:

      openssh:
        image: linuxserver/openssh-server
        ports: 
          - 2222:2222
        env:
          PASSWORD_ACCESS: true 
          USER_PASSWORD: "pass" 
          USER_NAME: "user"

      mailpit:
        image: axllent/mailpit
        ports:
          - 1025:1025
          - 8025:8025
        env:
          MP_SMTP_AUTH: "sender@example.org:fakepassword"
          MP_SMTP_AUTH_ALLOW_INSECURE: true
        # Options to speed up the "Waiting for all services to be ready" step
        options: >-
          --health-interval 1s
          --health-timeout 1s
          --health-retries 20

    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -e .[dev]

      - run: pytest -vv --log-cli-level info -s
