name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:

  examples:
    runs-on: ubuntu-latest

    services:

      openssh:
        image: linuxserver/openssh-server:10.2_p1-r0-ls220
        ports: 
          - 2222:2222
        env:
          PASSWORD_ACCESS: true 
          USER_PASSWORD: "pass" 
          USER_NAME: "user"

      mailpit:
        image: axllent/mailpit:v1.28
        ports:
          - 1025:1025
          - 8025:8025
        env:
          MP_SMTP_AUTH: "sender@example.org:fakepassword"
          MP_SMTP_AUTH_ALLOW_INSECURE: true
        # Options to speed up the "Waiting for all services to be ready" step
        options: >-
          --health-interval 1s
          --health-timeout 1s
          --health-retries 20

    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.12"

      - run: pip install -e .[dev]

      - run: pytest -vv --log-cli-level info -s
