name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:


  examples:
    runs-on: ubuntu-latest

    services:

      mailpit:
        image: axllent/mailpit
        ports:
          - 1025:1025
          - 8025:8025
        env:
          MP_SMTP_AUTH: "sender@example.org:fakepassword"
          MP_SMTP_AUTH_ALLOW_INSECURE: true
        # Options to speed up the "Waiting for all services to be ready" step
        options: >-
          --health-interval 1s
          --health-timeout 1s
          --health-retries 20

    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -e .

      - run: pytest -vv --log-cli-level info -s