name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:


  examples:
    runs-on: ubuntu-latest

    services:

      mailpit:
        image: axllent/mailpit
        ports:
          - 1025:1025
          - 8025:8025
        env:
          MP_SMTP_AUTH: "sender@example.org:fakepassword"
          MP_SMTP_AUTH_ALLOW_INSECURE: true
        options: >-
          --health-interval 2s
          --health-timeout 2s
          --health-retries 10

    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -e .

      - run: fractal-health tests/checks_config_fail.yaml -l INFO -o out1.txt -s
      - run: cat out1.txt
      - run: curl --silent http://localhost:8025/api/v1/messages | jq -r ".total"

      - run: fractal-health tests/checks_config_success.yaml -l INFO -o out2.txt -s
      - run: cat out2.txt
      - run: curl --silent http://localhost:8025/api/v1/messages | jq -r ".total"
