name: Publish to pypi

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  pypi-publish:

    name: Upload release to PyPI

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://test.pypi.org/p/fractal-healthcheck

    permissions:
      id-token: write

    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build
        run: |
          python -m pip install build
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
